all:
  hosts:
    node01:
     ansible_host: 192.168.2.1
     ip: 192.168.2.1
     access_ip: 192.168.2.1

  children:
    kube_control_plane:
      hosts:
        node01:

    etcd:
      hosts:
        node01:

    kube_node:
      hosts:
        node01:

    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:

    calico_rr:
      hosts: {}
