all:
  hosts:
    node01:
     ansible_host: 192.168.2.1
     ip: 192.168.2.1
     access_ip: 192.168.2.1
    node02:
     ansible_host: 192.168.2.2
     ip: 192.168.2.2
     access_ip: 192.168.2.2
    node03:
     ansible_host: 192.168.2.3
     ip: 192.168.2.3
     access_ip: 192.168.2.3

  children:
    kube_control_plane:
      hosts:
        node01:

    etcd:
      hosts:
        node01:

    kube_node:
      hosts:
        node01:
        node02:
        node03:

    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:

    calico_rr:
      hosts: {}
